### ISSUE TITLE
error "Internal Server Error" in ss 3.4.1

### ISSUE THREAD

**Issue by brasileric** [salted-herring/image-orientation-fixer#1]
When I use this module with SilverStripe 3.4.1 I get the error "Internal Server Error" when uploading an image:

![ss-fix](https://cloud.githubusercontent.com/assets/6453793/18987315/5401aabc-8701-11e6-8d24-5384c20346a4.jpg)

Without the module uploading is working well, but with wrong orientation :)

**Comment by leochenftw** [comment]
Hi Eric

Thanks for your feedback.

Because all this module does is to check the exif data of the image that the user uploads, and then use imagick (fallback to use GD) to manipulate the image based on the orientation value, if there is going to be a problem, it could be:
- assets directory permission setting
- Availabilities and accessibility of Imagick and GD module on the server
- incomplete upload

If reinstalling GD/Imagick doesn't fix the problem, can you open Chrome's inspector, and monitor Network tab, see what postback the server responds. 

Can you also send us the image that you were having problems with?

Cheers
Leo

**Comment by simonwinter** [comment]
@leochenftw I think we need more documentation around requirements. It's fair to assume that some users won't have ImageMagick installed.

**Comment by brasileric** [comment]
Hi.
Thanks for reply. ImageMagick is installed on this server and working well for some other functions. I'm gonna test it again today or tomorrow and let you know the results.

**Comment by brasileric** [comment]
Hi, I had to compile PHP with --enabled-exif . Now it works well.

Thanks!
